### ISSUE TITLE
Node2D.gd death counter fix

### ISSUE THREAD

**Issue by Nadelio** [krispyking24/godot-platformer#1]
``$"HUD/death counter"`` -> ``$"player/HUD/death counter"``

**Comment by krispyking24** [comment]
i have tried this but it still has the "Invalid set index 'text' (on base: 'null instance') with value of type 'String'." issue

**Comment by Nadelio** [comment]
Oh double check that your death counter is a label and that you are using the proper syntax for the label's text box.

**Comment by Nadelio** [comment]
[Label text field documentation](https://docs.godotengine.org/en/stable/classes/class_label.html#class-label-property-text)

**Comment by Nadelio** [comment]
you can also try ``$"player/HUD/death counter".set_text("Deaths: ", str(deaths))``

or just do ``$"player/HUD/death counter".text = "Deaths: ", str(deaths)``

**Comment by krispyking24** [comment]
the code is on the end of the node 2d script, i copied it to its own script and now it doesnt work at all. it worked fine before the moving of it to the player scene

**Comment by Nadelio** [comment]
Don't move it out of the node2D, it was fine where it was, you just forgot some syntax

``"text" + str(num)`` doesn't work like java, you need to instead do a comma:
``"text", str(num)``

**Comment by Nadelio** [comment]
The string syntax is very similar to python

**Comment by krispyking24** [comment]
i have $"player/HUD/death counter".set_text("Deaths: ", str(deaths)) which u said earlier and that's not working the other one u put  had its own issue

**Comment by Nadelio** [comment]
``$"HUD/death counter".text = "Deaths: " + str(deaths)`` -> ``$"player/HUD/death counter".text = "Deaths: ", str(deaths)``

I tested this today on my pc, and it works.
